# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-17 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialIndicatorModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('indicator_type', models.CharField(max_length=64)),
                ('indicator_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'financial_indicator',
            },
        ),
        migrations.CreateModel(
            name='FinancialStrategyModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('strategy_name', models.CharField(max_length=128)),
                ('indicators', models.TextField()),
            ],
            options={
                'db_table': 'financial_strategy',
            },
        ),
        migrations.AlterUniqueTogether(
            name='financialindicatormodel',
            unique_together=set([('indicator_type', 'indicator_name')]),
        ),
    ]
