# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicModel',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('up_to_market', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'basic',
            },
        ),
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.BasicModel')),
            ],
            options={
                'db_table': 'report',
            },
        ),
    ]
