# Generated by Django 2.0.3 on 2018-04-13 06:08

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerModel',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('detail', jsonfield.fields.JSONField(default=dict)),
            ],
            options={
                'db_table': 'crawler',
            },
        ),
    ]
